# In Travis extablish the following environment variables
# DEPLOY_TOKEN
# GITHUB_REPO
# EMAIL
# USERNAME

language: ruby
rvm:
- 2.3.1

before_install:
  - gem update --system
  - gem --version

before_script:
  - chmod +x ./script/cibuild

script: ./script/cibuild

# branch whitelist
branches:
  only:
  - master # builds only master branches

exclude: [vendor]

sudo: false
