language: ruby
rvm:
- 2.2

before_script:
  - chmod +x ./script/cibuild
  - chmod +x ./script/gh_pages_push

script: ./script/cibuild

after_success: ./script/gh_pages_push

# branch whitelist
branches:
  only:
  - master # builds only master branches
  
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - GITHUB_REPO: github.com/DIYbiosphere/sphere.dir.git
  - GITHUB_REPO_BRANCH: gh-pages

exclude: [vendor]

sudo: false