# In Travis extablish the following environment variables
# DEPLOY_TOKEN
# GITHUB_REPO
# EMAIL
# USERNAME

language: ruby
rvm:
- 2.3.1

before_install:
  - gem update --system
  - gem --version


before_script:
  - chmod +x ./script/cibuild
  - git config diff.renameLimit 999999
  - cp docs/guides/contributing.md docs/github/CONTRIBUTING.md
  - cp about/code-of-conduct.md docs/github/CODE_OF_CONDUCT.md

script: ./script/cibuild

env:
  global:
  - GITHUB_REPO: github.com/100ideas/sphere.git
  - DEPLOY_BRANCH: gh-pages
  - SOURCE_BRANCH: responsive-deploy
  - JEKYLL_ENV: production
  - NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer

exclude: [vendor]

sudo: false

deploy:
  provider: pages
  skip_cleanup: true
  target_branch: gh_pages

notifications:
  # TODO configure diybiosphere gitter integration webhook
  # webhooks:
  #   urls:
  #     - https://webhooks.gitter.im/e/XXXXXXXXXXXXXXXXXXXX
  #   on_success: change  # options: [always|never|change] default: always
  #   on_failure: always  # options: [always|never|change] default: always
  #   on_start: false     # default: false
