# In Travis extablish the following environment variables
# ALGOLIA_API_KEY
# ALGOLIA_APPLICATION_ID
# ALGOLIA_INDEX_NAME
# DEPLOY_TOKEN
# GITHUB_REPO
# EMAIL
# USERNAME
# GH_BASIC_CLIENT_ID
# GH_BASIC_SECRET_ID

language: ruby
rvm:
- 2.3.1

before_install:
  - gem update --system
  - gem --version

before_script:
  - chmod +x ./script/cibuild

script: ./script/cibuild

# branch whitelist
branches:
  only:
  - master # builds only master branches

exclude: [vendor]

sudo: false
