language: ruby
rvm:
- 2.3.1

before_install:
  - gem update --system
  - gem --version

before_script:
  - chmod +x ./script/cibuild
  - chmod +x ./script/gh_pages_push

script:
   - ./script/cibuild

after_success: ./script/gh_pages_push

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - GITHUB_REPO: github.com/DIYbiosphere/sphere.git
  - DEPLOY_BRANCH: gh-pages
  - SOURCE_BRANCH: master


exclude: [vendor]

sudo: false

# In Travis extablish the following environment variables
# DEPLOY_TOKEN
# GITHUB_REPO
# EMAIL
# USERNAME
