# Site settings
title: DIYbiosphere
description: "An open source project to connect DIYBio Initiatives from all over the world"
baseurl: "" # the subpath of your site, e.g. /blog
url: "sphere.diybio.org"
permalink: /updates/:year/:month/:day/:title
repository: DIYbiosphere/sphere
github_comments_repository:  diybiosphere/talk
github_username: DIYbiosphere
twitter:
  username: DIYbiosphere


# Excluded files and dirs
exclude:
  - vendor
  - script
  - Gemfile
  - Gemfile.lock
  - README.md
  - DataReusePlan.txt
  - .assets-cache
  - .sass-cache
  - node_modules
  - semantic.json
  - package-lock.json
  - package.json

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge

github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false

# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes


plugins:
  - jemoji
  - jekyll-gist
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-github-metadata
  - jekyll-git_metadata
  - jekyll-last-modified-at
  - jekyll-feed
  - jekyll-avatar
  - jekyll-toc #https://github.com/toshimaru/jekyll-toc/
  - jekyll-timeago
  - jekyll-giphy

# Collections
collections:
  projects:
    title: Projects
    output: true
    collection: Project
  startups:
    title: Startups
    output: true
    collection: Startup
  labs:
    title: Labs
    output: true
    collection: Lab
  incubators:
    title: Incubators
    output: true
    collection: Incubator
  groups:
    title: Groups
    output: true
    collection: Group
  networks:
    title: Networks
    output: true
    collection: Network
  events:
    title: Events
    output: true
    collection: Event
  others:
    title: Others
    output: true
    collection: Other

# Default Values
defaults:
  -
    scope:
      type: posts
    values:
      layout: post
  -
    scope:
      type: projects
    values:
      layout: entry
      collection: Project
  -
    scope:
      type: startups
    values:
      layout: entry
      collection: Startup
  -
    scope:
      type: labs
    values:
      layout: entry
      collection: Lab
  -
    scope:
      type: incubators
    values:
      layout: entry
      collection: Incubator
  -
    scope:
      type: groups
    values:
      layout: entry
      collection: Group
  -
    scope:
      type: networks
    values:
      layout: entry
      collection: Network
  -
    scope:
      type: events
    values:
      layout: entry
      collection: Event
  -
    scope:
      type: others
    values:
      layout: entry
      collection: Other

  -
    scope:
      type: pages
    values:
      layout: page


# PLUGIN CONFIGURATIONS

# Jekyll assets plugin
assets:
  compress:
    css: sass
    js: uglifier
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  assets:
    - "*.png"
    - "*.gif"
    - "*.jpg"
    - "*.svg"
  sources:
    - assets
    - assets/img
    - assets/js
    - assets/css
    - assets/gif

# Jekyll-Tagging: https://github.com/pattex/jekyll-tagging/
tag_page_layout: tag_page
tag_page_dir: tag


# AlgoliaSearch-Jekyll: https://github.com/algolia/algoliasearch-jekyll/
algolia:
  application_id: 'ITI5JHZJM9'
  index_name: 'diybiosphere'
  search_only_api_key: 'b427318cf6d881e5d3ffd84adf39219e'
  indexing_batch_size: 100
  nodes_to_index: 'p,blockquote,li'
  files_to_exclude:
    - index.html
    - 404.html
    - entries.html
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - about/*.md
    - about/*/*.md
    - docs/*.md
    - docs/*/*.md
    - docs/*/*/*.md
    - docs/*/*/*.md
  settings:
    searchableAttributes:
      - title
      - subtitle
      - hosts
      - hostsSentence
      - hostsArray
      - partners
      - partnersSentence
      - partnersArray
      - city
      - state
      - country
      - content
      - tags
      - collection
      - predecessor
      - successor
    attributesToRetrieve:
      - title
      - subtitle
      - url
      - type-org
      - uberimage
      - hosts
      - hostsSentence
      - hostsArray
      - partners
      - partnersSentence
      - partnersArray
      - city
      - state
      - country
      - content
      - tags
      - tagsExist
      - collection
      - start-date
      - end-date
      - predecessor
      - successor
      - status
      - project
      - lab
      - group
      - network
      - startup
      - incubator
      - event
      - other
      - last_modified_at
      - timestamp
    attributesForFaceting:
      - collection
      - type-org
      - city
      - state
      - country
      - tags
      - status
      - start-date
      - end-date
      - status
    attributesToHighlight:
      - title
      - subtitle
      - hosts
      - hostsSentence
      - hostsArray
      - partners
      - partnersSentence
      - partnersArray
      - city
      - state
      - country
      - content
      - tags
      - collection
      - predecessor
      - successor
    attributesToSnippet: ['content:10']
    highlightPreTag: <span class="search-highlight">
    highlightPostTag: </span>
