# Site settings
title: DIYbiosphere
email: contact@contact.com
description: "A collaborative directory of Do-it-Yourself Biology initiatives"
baseurl: "" # the subpath of your site, e.g. /blog
url: "sphere.diybio.org"
permalink: /news/:year/:month/:day/:title
repository: "DIYbiosphere/sphere.dir"
github_username: "DIYbiosphere"
twitter:
  username: DIYbiosphere


# Excluded files and dirs
exclude: [script, Gemfile, Gemfile.lock, README.md, DataReusePlan.txt]

# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes

# Build settings
markdown: kramdown

gems:
  - jemoji
  - jekyll-gist
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-github-metadata

# Collections
collections:
  database:
    title: Database
    output: true
    permalink: /database/:path
  events:
    title: Ebents
    output: true
    permalink: /events/
  others:
    title: Others
    output: true
    permalink: /others/

# Defaul Values
defaults:
  -
    scope:
      path: ''
    values:
      layout: landing
  -
    scope:
      type: posts
    values:
      layout: post
  -
    scope:
      type: database
    values:
      layout: entry
      permalink: /database/:path
  -
    scope:
      type: events
    values:
      layout: entry
      permalink: /events/:title
  -
    scope:
      type: others
    values:
      layout: entry
      permalink: /others/:title
